Add Backend Sandbox Script
TeamUnibuc/MDS pull request #10
Opened 2021-02-20 18:29 UTC by theodormoroianu

This PR adds a script for automatic bot testing, partially closing issue #9.

2021-02-20 23:34 UTC, ConstantinDragancea approved these changes
Seems legit

2021-02-21 12:09 UTC, stelianchichirim approved these changes
Nice

2021-02-21 12:25 UTC, Rpd-Strike requested changes
Cool, just modify that command line :)

2021-02-21 12:25 UTC, Rpd-Strike commented on Engine/Grader/enginelib.hpp
> +
Make a line for each of the arguments (e.g. stdin, stdout ....)

2021-02-21 13:54 UTC, Rpd-Strike approved these changes
Neat

2021-02-21 13:54 UTC, merged