Add New Game DB Call
TeamUnibuc/MDS pull request #52
Opened 2021-04-29 14:03 UTC by theodormoroianu

This PR adds a sample addition into the database of a new game.

2021-04-29 14:20 UTC, Rpd-Strike requested changes

2021-04-29 14:20 UTC, Rpd-Strike commented on backend/src/models/GamesModel.ts
> +export const GamesDB = mongoose.model<GamesDoc>('Games', GamesSchema);
E putin confuzant <Model>DB, mai bine <NumeModel>Model deoarece e confuzant sa faci `new GamesDB()` si asupra astuia faci save. Nu prea are sens sa creezi o BD si apoi sa o salvezi :)))

2021-04-29 14:20 UTC, Rpd-Strike commented on backend/src/models/GamesModel.ts
> +export const GamesDB = mongoose.model<GamesDoc>('Games', GamesSchema);
Tocmai de-asta e common practice sa faci de exemplu `CarModel = mongoose.model<...>(...)`. Ca sa aiba sens `new CarModel()`

2021-04-30 13:36 UTC, theodormoroianu commented on backend/src/models/GamesModel.ts
> +export const GamesDB = mongoose.model<GamesDoc>('Games', GamesSchema);
Am modificat sa se cheme `xxxxModel`.

2021-04-30 14:01 UTC, Rpd-Strike approved these changes
Super, acuma daca va vin idei la ce mai tinem minte pt useri, sa scrieti undeva.

2021-04-30 14:01 UTC, felixp72 commented on backend/src/models/GamesModel.ts
> +export const GamesDB = mongoose.model<GamesDoc>('Games', GamesSchema);
Tot in aceeasi idee, pune interfetele la singular. Imi zgarie OCD-ul `GamesModel`. GameModel. interfata `GameModel` poti sa o lasi simplu `Game`. Poti si sa lasi numele fisierului `Game.ts` simplu, ca e deja in folderul `models`. ms :D

2021-04-30 14:08 UTC, merged